### ISSUE TITLE
application/x-www-form-urlencoded not supported?

### ISSUE THREAD

**Issue by j-5-s** [doomhz/node-lambda-req#2]
Looks like form uploads are not supported, is that correct. Meaning the library only supports post json/querystring parameters. Or, am i using the library incorrectly? If i try to parse a application/x-www-form-urlencoded body, [the code](https://github.com/doomhz/node-lambda-req/blob/master/src/LambdaReq.js#L131) does not look at a content-type header and parse accordingly, right? It throws an error when you do this.

**Comment by doomhz** [comment]
Yes, you're right, multipart is not supported because I have the uploads directly to S3 with a signed URL. The lambda is triggered on s3:put event afterwards as described here `http://docs.aws.amazon.com/lambda/latest/dg/with-s3.html`

**Comment by j-5-s** [comment]
Yes, thank you. I realized uploading multi-part (images) through gateway to lambda was an anti-pattern after struggling with it for so long. Going straight into s3 makes more sense.
